services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  resume-analyzer:
    build:
      context: .
      dockerfile: resume_analyzer/Dockerfile
    ports: ["9000:9000"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - resume-analyzer
      - postgres
    environment:
      DB_HOST: postgres           # <— use service name
      DB_PORT: 5432               # <— container port
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      RESUME_ANALYZER_BASE_URL: http://resume-analyzer:9000
    ports: ["8080:8080"]

volumes:
  postgres-data:
